version: '3.3'
services:

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../frontend/:/app/result_build/

  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    expose:
      - 8000
    restart: always
    volumes:
      - ../backend/:/app/backend_build/

  nginx:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/